# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "json_api_client", github: "chingor13/json_api_client"

gem "pry"
